#!/usr/bin/env bash
#
# scripts/weekly-content.sh
#
# Génère un nouvel article Actualités via l'agent content-writer et le commite
# dans une branche dédiée pour validation humaine.
#
# Usage manuel :
#   ./scripts/weekly-content.sh
#
# Usage CI (GitHub Action `weekly-content.yml`) : lancé chaque lundi 08:00 UTC.
#
# Prérequis :
#   - Claude Code CLI installé et authentifié (`claude --version` OK)
#   - Variable d'env ANTHROPIC_API_KEY si exécution headless
#   - Git configuré
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

WEEK_TAG="$(date +%Y-W%V)"
BRANCH="content/actualites-${WEEK_TAG}"

echo "▶ Création de la branche $BRANCH"
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

echo "▶ Invocation de l'agent content-writer…"
# Le flag --agent pointe vers .claude/agents/content-writer.md
# --print sort le résultat et quitte (mode headless).
claude \
  --agent content-writer \
  --print \
  "Rédige l'article Actualités de la semaine ${WEEK_TAG}. Respecte strictement le brief de l'agent. Vérifie d'abord content/actualites/ pour éviter les doublons. Sors le fichier MDX complet avec frontmatter et enregistre-le au bon chemin."

echo "▶ Vérification du fichier produit"
NEW_FILE="$(git status --porcelain content/actualites/ | awk '/^\?\?/ {print $2}' | head -n1)"
if [ -z "$NEW_FILE" ]; then
  echo "⚠ Aucun nouvel article détecté. Abandon."
  git checkout -
  exit 1
fi

echo "▶ Article généré : $NEW_FILE"

git add "$NEW_FILE"
git commit -m "content(actualites): article hebdo ${WEEK_TAG}

Generated by content-writer agent."

echo "▶ Push de la branche"
git push -u origin "$BRANCH"

echo "✓ Article prêt pour relecture sur la branche $BRANCH"
echo "  Ouvrez une PR pour valider et merger vers main."
